export const ECO_TIPS = [
"Always rinse containers before recycling to avoid contamination. Singapore's recycling rate drops significantly if food waste is present,",
"Did you know? Singapore recycles about 60% of its waste, but the target is 70% by 2030!",
"Plastic bags should never go in the blue bins. Instead, bring them back to participating supermarkets for collection",
"Flatten your cardboard boxes before recycling to save space in the bin",
"Compost food scraps instead of throwing them away. Singapore’s composting facilities are growing, making it easier to reduce waste!",
"Did you know? Singapore imports almost all its food, so composting at home helps reduce food waste and save resources",
"Don’t throw away old electronics—take them to designated e-waste collection points to protect the environment",
"Recycling a single aluminium can saves enough energy to power a television for 3 hours—so make sure to recycle yours!",
"Always separate recyclables like paper, plastic, glass, and metals to help the sorting process. Check if an item is recyclable before discarding it",
"Used takeaway containers often cannot be recycled in Singapore's blue bins, as they may contain food residue",
"Did you know? Singapore’s National Environment Agency (NEA) has set up more than 1,000 recycling bins across the island",
"Plastic straws and cutlery are not recyclable. Try bringing your own reusable items to reduce waste",
"Don’t mix recyclables with food waste—only clean, dry items can be recycled",
"Check the recycling symbol on plastics. Only types 1 and 2 are widely accepted in Singapore’s blue bins",
"Did you know? Singapore is turning its waste into energy through the Tuas Incineration Plant, reducing landfill use!",
"Don’t recycle plastic bags or styrofoam—dispose of them in the general waste bins instead",
"Separate batteries from general waste and drop them at collection points for proper disposal",
"Old clothes can be donated instead of discarded. Many charity shops in Singapore welcome used clothing donations",
"Did you know? Singapore’s recycling system includes recycling of e-waste like mobile phones and computers at designated centres",
"Remember to remove caps and lids from bottles before recycling them. They are usually made of different materials and require separate processing",
"Compost yard waste like leaves and grass at home, or use the free collection services provided by NEA",
"Don’t put wet items like tissues or used napkins into the recycling bin—they are not recyclable",
"Check the labels for packaging that can be recycled. If unsure, it’s better to dispose of it properly than risk contamination",
"Did you know? Singapore has a zero-waste goal by 2030—recycling is a key part of the plan to reduce waste",
"Clothing made from synthetic materials may not be recyclable, so be mindful when discarding fabric items",
"Before you toss it, ask: Can this item be reused or repurposed? Reducing waste by reusing is better than recycling",
"Remember to deposit your recyclables in the correct bins—plastic bottles go in the blue bins, but not the plastic bags.",
"Recycling one ton of paper saves 17 trees, 380 gallons of oil, and 3 cubic yards of landfill space",
"Did you know? Glass can be recycled indefinitely without losing quality, making it a valuable material for sustainability",
"Keep electronics out of the trash! Old phones, computers, and other devices contain valuable metals that can be recycled",
"Never throw away used batteries—they contain toxic chemicals and should be disposed of at specialized recycling facilities",
"Compostable plastics are not always compostable in municipal facilities—check your local guidelines before disposal",
"Did you know? Recycling aluminum uses 95% less energy than producing new aluminum from raw materials",
"Reuse gift wrapping and ribbons to reduce waste during holidays and special occasions",
"Consider buying products made from recycled materials, as it helps reduce demand for raw materials and saves energy",
"Food containers made from polystyrene foam (Styrofoam) cannot be recycled in most areas—avoid buying them when possible",
"Donate unwanted items like furniture, clothes, and books to charity instead of throwing them away",
"Did you know? A single plastic bottle can take up to 1,000 years to decompose in a landfill",
"Recycling your old magazines, newspapers, and catalogs is a great way to reduce waste while supporting sustainability",
"Don’t recycle dirty or greasy pizza boxes—they contaminate the rest of the recycling",
"Always check for the recycling number on plastic packaging. Numbers 1 and 2 are commonly accepted for recycling",
"Did you know? More than 8 million tons of plastic enter the ocean every year, harming marine life and ecosystems",
"Instead of throwing away broken household items, try fixing them. Repair cafes are a growing trend that promotes reusability",
"Recycling plastic bottles reduces the demand for new plastic production, cutting down on harmful emissions and waste",
"Did you know? The first recycling bin was introduced in the United States in 1970",
"Rinse and dry recyclables before placing them in the bin to prevent contamination and improve quality",
"Check with your local waste management services to know which materials are accepted for recycling in your area",
"Did you know? Recycled paper uses 60% less energy than making new paper from wood",
"Try to avoid buying products with excessive packaging, as it often ends up in landfills rather than being recycled",
"Instead of using disposable plates, cups, and cutlery, opt for reusable alternatives to reduce plastic waste",
"Recycling is not only about what you discard—it’s also about purchasing sustainably produced goods to reduce waste upfront",
"Did you know? In 2020, only 9% of the world’s plastic waste was recycled, according to the UN.",
"By reusing materials like glass jars and old containers, you reduce the need for new packaging and conserve resources",
"Educate others about the importance of recycling and how to recycle correctly—it helps make the process more effective for everyone",
"Did you know? The Eiffel Tower is made of 100% recycled steel, showing how recycling can create iconic structures",
"Always check for local guidelines when recycling, as different regions have different recycling rules and capabilities",
"Did you know? The first public recycling bin was introduced in 1975 in the UK, marking the start of organized recycling programs",
"Take part in local community recycling programs to help reduce the amount of waste going to landfills and incinerators",
"Use digital instead of paper documents whenever possible to reduce paper waste",
"Did you know? Plastic bags are often the number one contaminant in curbside recycling programs, so avoid them!",
"Instead of buying bottled water, use a reusable water bottle to reduce plastic waste",
"Recycling not only saves natural resources, but it also reduces greenhouse gas emissions and helps fight climate change",
"Did you know? Recycling aluminum cans saves up to 95% of the energy it takes to make a new can from raw materials",
"Set up a recycling station at home or work with labeled bins for paper, glass, plastic, and metal to streamline the process",
"Before recycling, make sure items are empty and clean, as food residue can spoil an entire batch of recyclables",
"Did you know? In 2018, 9.5 million metric tons of recyclable plastic were lost to landfill due to contamination from food waste.",
"Consider buying second-hand goods to help reduce demand for new products and save energy on manufacturing processes",
"Did you know? The U.S. recycles less than one-third of its plastic waste—so there’s plenty of room for improvement!",
"Recycling can create new jobs and support the economy while benefiting the environment, which is a win-win situation",
"Consider joining a local clean-up event to help recycle beach and park waste, keeping public spaces free from litter",
"Did you know? Recycling one ton of paper saves 17 trees, and it takes 4,000 kWh of energy to produce new paper from raw wood",
"Be mindful of mixed materials—check labels to know whether they can be recycled or if they need to be separated first",
"Switching to reusable bags, containers, and cups can help eliminate the use of thousands of single-use plastics each year",
"Did you know? In the future, cities around the world are investing in AI to sort recyclables more efficiently and reduce contamination",
"By recycling, you're helping create a circular economy where materials are reused and repurposed instead of being wasted",
"Be mindful of electronic waste! Computers and phones contain valuable metals like gold and silver that can be recycled and repurposed",
"Did you know? Over 40% of plastic packaging in the world is single-use, but it can be avoided by adopting reusable options.",
"Keep up with the latest recycling innovations—companies are now developing biodegradable plastics and edible packaging to reduce waste",
"Recycling helps protect wildlife by reducing the amount of waste that can harm animals in landfills or the ocean",
"Did you know? The ‘Reduce, Reuse, Recycle’ motto first appeared in the 1970s during the environmental movement",
"Be aware that some cities offer curbside composting services—check if your area offers this convenient way to manage organic waste.",
"Did you know? The first recycling plant in the U.S. opened in 1972 in New York City, pioneering the recycling movement in America.",
];